# This file was generated by GoReleaser. DO NOT EDIT.
class DocCli < Formula
  desc "OpenContent CLI Tools"
  homepage "https://navigaglobal.com"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/doc-cli/0.1.0/doc-cli_macOS_64-bit.zip"
    sha256 "d9607d1bcbdb6c1ee774d8bf991850c7cc4011d5adc5e0e9d1a2cdfb1693358c"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/doc-cli/0.1.0/doc-cli_Tux_64-bit.zip"
    sha256 "9d05388b6f9cbb5c4c257b237bf69e408f7acc9df77501da696e9f927a2c856e"
  end

  def install
    bin.install "mime-check"
    bin.install "uuid-check"
    bin.install "transform-check"
    bin.install "oc2kafka"
  end
end
