# This file was generated by GoReleaser. DO NOT EDIT.
class IngesterLambdaGui < Formula
  desc "Ingester Lambda GUI Tool"
  homepage "https://navigaglobal.com"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/ingester-lambda-gui/0.1.0/ingester-lambda-gui_macOS_64-bit.zip"
    sha256 "3cff469c39eb43e10baf142babc03bc344022d083ba8892b57f82c71100730ea"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/ingester-lambda-gui/0.1.0/ingester-lambda-gui_Tux_64-bit.zip"
    sha256 "a594e2576fe41e6a9139d631e900a864e6a84aaa0747a80ad8cf33d109119a3a"
  end

  def install
    bin.install "ingester-gui"
  end
end
