# This file was generated by GoReleaser. DO NOT EDIT.
class IngesterLambdaGui < Formula
  desc "Ingester Lambda GUI Tool"
  homepage "https://navigaglobal.com"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/ingester-lambda-gui/0.1.0/ingester-lambda-gui_macOS_64-bit.zip"
    sha256 "f4ddf43371890750d9097d1203256672f9c9e091c1d1988caee1f9b6afd9e1e4"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/ingester-lambda-gui/0.1.0/ingester-lambda-gui_Tux_64-bit.zip"
    sha256 "26540cee2c1848bc3442ad1a2873c9f3eeb41bdbd51e814b74ffcd545bacf07a"
  end

  def install
    bin.install "ingester-gui"
  end
end
