# This file was generated by GoReleaser. DO NOT EDIT.
class IngesterLambdaTools < Formula
  desc "Ingester Lambda Tools"
  homepage "https://navigaglobal.com"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/ingester-lambda-tools/0.1.0/ingester-lambda-tools_macOS_64-bit.zip"
    sha256 "45258798c965e09c1e9f1380be993055e2b6f79bb65303f33eef72f855d71922"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/ingester-lambda-tools/0.1.0/ingester-lambda-tools_Tux_64-bit.zip"
    sha256 "c186296f0a08fd947cf9951be90c1a4f5e5113451d7b65a578cdfdaa6aaadc58"
  end

  def install
    bin.install "ingester-cli"
    bin.install "ingester-doc"
  end
end
