# This file was generated by GoReleaser. DO NOT EDIT.
class IngesterLambdaTools < Formula
  desc "OpenContent CLI Tools"
  homepage "https://navigaglobal.com"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/ingester-lambda-tools/0.1.0/ingester-lambda-tools_macOS_64-bit.zip"
    sha256 "cd69404e2c81e0fadc9e5c59755d6961d1eebde797f29ecd7162cc91924a60a9"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/ingester-lambda-tools/0.1.0/ingester-lambda-tools_Tux_64-bit.zip"
    sha256 "bafe2168a11489a0b8abe3a24bb2bf40ac20f2e0e09733a420e0dd8acbf4073a"
  end

  def install
    bin.install "ingester-cli"
    bin.install "ingester-doc"
  end
end
