# This file was generated by GoReleaser. DO NOT EDIT.
class IngesterLambdaTools < Formula
  desc "Ingester Lambda Tools"
  homepage "https://navigaglobal.com"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/ingester-lambda-tools/0.1.0/ingester-lambda-tools_macOS_64-bit.zip"
    sha256 "c7bc3bb6a340f5722c94e58f84ab573e83b380e0d5f21c2182d5a8bbf2fb0b71"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/ingester-lambda-tools/0.1.0/ingester-lambda-tools_Tux_64-bit.zip"
    sha256 "17ac509bffb2348ab93c4cec06f274bee5d04e61f69f7e599378134b4baf19d2"
  end

  def install
    bin.install "ingester-cli"
    bin.install "ingester-doc"
  end
end
