# This file was generated by GoReleaser. DO NOT EDIT.
class IngesterLambdaGui < Formula
  desc "Ingester Lambda GUI Tool"
  homepage "https://navigaglobal.com"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/ingester-lambda-gui/0.1.0/ingester-lambda-gui_macOS_64-bit.zip"
    sha256 "d318d61d224b2ef66d94c52765c1a7a9a960e72c565bdc790d4a66e83c7107ca"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/ingester-lambda-gui/0.1.0/ingester-lambda-gui_Tux_64-bit.zip"
    sha256 "cf872b65ebc5b10cc48bdd6d8aff576fc351533e20f69a606cce6557f69cf691"
  end

  def install
    bin.install "ingester-gui"
  end
end
