# This file was generated by GoReleaser. DO NOT EDIT.
class MimeCheck < Formula
  desc "Check OpenContent for mimetype inconsistencies"
  homepage "https://navigaglobal.com"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/mime-check/0.1.0/mime-check_macOS_64-bit.zip"
    sha256 "6f07af80e1e5c2e2e5f081b3742f8c70c7bdff29e41bde78b36e8c4a90b7b637"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/mime-check/0.1.0/mime-check_Tux_64-bit.zip"
    sha256 "0b2adbcac2d0fc3dc803b26dc08e1311595f7a6c8a98344255cd58ca65c7f54b"
  end

  def install
    bin.install "mime-check"
    bin.install "uuid-check"
    bin.install "transform-check"
    bin.install "oc2kafka"
  end
end
