# This file was generated by GoReleaser. DO NOT EDIT.
class MimeCheck < Formula
  desc ""
  homepage ""
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/mime-check/0.1.0/mime-check_macOS_64-bit.zip"
    sha256 "54597d2610790c66823775b1bf4b1bd80e90995998c69906565a5ee8adac8885"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/mime-check/0.1.0/mime-check_Tux_64-bit.zip"
    sha256 "14079c7da2548e7a5c43159be794123655aa1bdd56e45f97fc3473eed28dfc92"
  end

  def install
    bin.install "mime-check"
    bin.install "uuid-check"
    bin.install "transform-check"
    bin.install "oc2kafka"
  end
end
