# This file was generated by GoReleaser. DO NOT EDIT.
class MimeCheck < Formula
  desc ""
  homepage ""
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/mime-check/0.1.0/mime-check_macOS_64-bit.zip"
    sha256 "3caef993e7a763b84102e77f67a4235b6ac8bc0eb9973233a2f21b431e361785"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/mime-check/0.1.0/mime-check_Tux_64-bit.zip"
    sha256 "e5526562d6de1ebb0e68946dd58ced40eba1b321699f9f76ac0525ab263c5a5b"
  end

  def install
    bin.install "mime-check"
    bin.install "uuid-check"
    bin.install "transform-check"
    bin.install "oc2kafka"
  end
end
