# This file was generated by GoReleaser. DO NOT EDIT.
class Oc2kafka < Formula
  desc "Generate Kafka events from OpenContent documents"
  homepage "https://navigaglobal.com"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/oc2kafka/0.1.0/oc2kafka_macOS_64-bit.zip"
    sha256 "7645dfe69d6ebb3767aa42907d205c9dd8fdc500d117e8b2f88c3014922dd6c7"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/oc2kafka/0.1.0/oc2kafka_Tux_64-bit.zip"
    sha256 "539dc29986dac200309bbead6c4060422799237a1bf01b8fa42f5f389d1d212f"
  end

  def install
    bin.install "mime-check"
    bin.install "uuid-check"
    bin.install "transform-check"
    bin.install "oc2kafka"
  end
end
