# This file was generated by GoReleaser. DO NOT EDIT.
class Oc2kafka < Formula
  desc ""
  homepage ""
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/oc2kafka/0.1.0/oc2kafka_macOS_64-bit.zip"
    sha256 "77d213480702d73364cb038930e0d056909760ba0a8b1d05c04dcdc1b898df26"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/oc2kafka/0.1.0/oc2kafka_Tux_64-bit.zip"
    sha256 "cd73bb09bad0bbb9204547ab4970a33840d13dafb6fe63e4406c5589c43c198f"
  end

  def install
    bin.install "mime-check"
    bin.install "uuid-check"
    bin.install "transform-check"
    bin.install "oc2kafka"
  end
end
