# This file was generated by GoReleaser. DO NOT EDIT.
class Oc2kafka < Formula
  desc ""
  homepage ""
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/oc2kafka/0.1.0/oc2kafka_macOS_64-bit.zip"
    sha256 "a49f345b5fc679876473952e0e64de36df39aa1e8826f63f44456b81a010c69a"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/oc2kafka/0.1.0/oc2kafka_Tux_64-bit.zip"
    sha256 "97d6b4508883e12a7962d2613ab3bec706a1e8f586242c5b4fdf9c2e15065479"
  end

  def install
    bin.install "mime-check"
    bin.install "uuid-check"
    bin.install "transform-check"
    bin.install "oc2kafka"
  end
end
