# This file was generated by GoReleaser. DO NOT EDIT.
class TransformCheck < Formula
  desc "Roundtrip transform NewsML->Navigadoc->NewsML to check for problems"
  homepage "https://navigaglobal.com"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/transform-check/0.1.0/transform-check_macOS_64-bit.zip"
    sha256 "54c449c853db9b1a5c5072b1a3371360c85e1f697ec0cd137190902e85e1f1e4"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/transform-check/0.1.0/transform-check_Tux_64-bit.zip"
    sha256 "dceafe1b29bf725e7f8dc0deb4724ae88ab0395167cb5fe31d0aa426af7b0091"
  end

  def install
    bin.install "mime-check"
    bin.install "uuid-check"
    bin.install "transform-check"
    bin.install "oc2kafka"
  end
end
