# This file was generated by GoReleaser. DO NOT EDIT.
class TransformCheck < Formula
  desc ""
  homepage ""
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/transform-check/0.1.0/transform-check_macOS_64-bit.zip"
    sha256 "8c52781cd181e4ce2f11e6a40bb4a9c40deca7ee581592792b19e6bb2d0d957f"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/transform-check/0.1.0/transform-check_Tux_64-bit.zip"
    sha256 "54c50143a4f11825da0ec98d4d4b24b28ffc2d7597cdac96975e2e93f523459e"
  end

  def install
    bin.install "mime-check"
    bin.install "uuid-check"
    bin.install "transform-check"
    bin.install "oc2kafka"
  end
end
