# This file was generated by GoReleaser. DO NOT EDIT.
class UuidCheck < Formula
  desc "Check OpenContent for missing/invalid UUIDs"
  homepage "https://navigaglobal.com"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/uuid-check/0.1.0/uuid-check_macOS_64-bit.zip"
    sha256 "5f8601f4eb8ea0d6d37bcf8550fe2cdf53858ab8d916dbb09eff7d3d3141d159"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/uuid-check/0.1.0/uuid-check_Tux_64-bit.zip"
    sha256 "ace13fdab72ce479f40b8db089a93497f4725b864e71e7fddbb1ea8ef17a3894"
  end

  def install
    bin.install "mime-check"
    bin.install "uuid-check"
    bin.install "transform-check"
    bin.install "oc2kafka"
  end
end
