# This file was generated by GoReleaser. DO NOT EDIT.
class UuidCheck < Formula
  desc ""
  homepage ""
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/uuid-check/0.1.0/uuid-check_macOS_64-bit.zip"
    sha256 "3f2ebc98784a045a6f7db003eaba3e58fde7ecf6ae68b63dcb5222c0f7eb4609"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/uuid-check/0.1.0/uuid-check_Tux_64-bit.zip"
    sha256 "4e793b096aef098c85535e17a2049cf7a439c5f198d835590ec6f0c28f7a0c0b"
  end

  def install
    bin.install "mime-check"
    bin.install "uuid-check"
    bin.install "transform-check"
    bin.install "oc2kafka"
  end
end
